### ISSUE TITLE
CC Ubuntu 20.04 image missing libmysqlclient.so.21

### ISSUE THREAD

**Issue by themorey** [Azure/cyclecloud-slurm#123]
**CC**:  8.4.0
**Cluster-Init**:  3.0.1
**Slurm ver**:  22.05.3-1

Slurmdbd failed to start with following message:
` slurmdbd: error: plugin_load_from_file: dlopen(/usr/lib64/slurm/accounting_storage_mysql.so): libmysqlclient.so.21: cannot open shared object file: No such file or directory`

Workaround:
`apt install -y libmysqlclient-dev`

**Comment by ryanhamel** [comment]
Fixed in 3.0.3
