### ISSUE TITLE
Cluster creation fails when accounting is selected because of new MariaDB certificate

### ISSUE THREAD

**Issue by matteoacrossi** [Azure/cyclecloud-slurm#125]
With latest version of Cyclecloud and slurm template, the cluster creation fails when setting up slurm accounting with Azure MariaDB. The reason is that the old certificate is used, i.e. these instructions are not followed: https://learn.microsoft.com/en-us/azure/mariadb/concepts-certificate-rotation

**Comment by jpROC1** [comment]
Also having this issue.

**Comment by jgregorcmh** [comment]
Same issue applies to Azure MySQL.  The BaltimoreCyberTrustRoot.crt.pem is hardcoded in both the 2.7.X and 3.X templates.  Release notes on 2.7.3 says you can now pass a value, but I haven't tried that version.  Template version 3.0.1 does not incorporate that fix.  I have had to edit the installer to set CA certs to be the concatenation of the Baltimore and the Digicert.

**Comment by ryanhamel** [comment]
Fixed in 3.0.3
