### ISSUE TITLE
Login node configuration missing from 3.0.1

### ISSUE THREAD

**Issue by mani91-ug** [Azure/cyclecloud-slurm#129]
Login nodes no longer have consistent hostnames and are not configured in release 3.0.1. Looking at the code, it seems that Chef recipes are absent which were present in previous releases. Pre-release 3.0.2 appears to attempt to rectify this but pointing my deployment to use that results the cluster being completely unable to start up.

**Comment by ryanhamel** [comment]
Fixed in 3.0.3
