### ISSUE TITLE
Azure CycleCloud/Slurm default cluster config creates an (unused) Shared disk even when selecting to mount Shared from an NFS Server

### ISSUE THREAD

**Issue by garymansellricardo** [Azure/cyclecloud-slurm#196]
Hi,

I am using the default Slurm cluster config template from version 3.0.1 - and it seems to create a 2GB Azure managed disk for the shared filesystem on the scheduler node even though I am mounting /shared from an NFS file server (the cyclecloud server). I think this should not be needed?

Here is a screenshot showing the disk in Azure:

![2024-01-10_09h53_17](https://github.com/Azure/cyclecloud-slurm/assets/63644611/320fec4f-297d-4338-9a1f-caea6f190403)

Here, you can see the disk at the Linux OS (as sdb and no mount point):

[root@nemospot-scheduler ~]# lsblk -o NAME,HCTL,SIZE,MOUNTPOINT | grep -i "sd"
sda     0:0:0:0      30G
sdb     0:0:0:1       2G
sdc     1:0:0:0      60G
├─sdc1             1000M /boot
├─sdc2             58.5G /
├─sdc14               4M
└─sdc15             495M /boot/efi
sdd     1:0:0:1      75G
└─sdd1               75G /mnt

Here, you can see /shared mounted from the CycleCloud server via NFS:

[root@nemospot-scheduler ~]# mount | grep shared
azu-nemo-srv:/shared on /shared type nfs4 (rw,relatime,vers=4.1,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,clientaddr=192.168.140.132,local_lock=none,addr=192.168.140.20)

Would be good not to incur unnecessary Azure costs...

**Comment by garymansellricardo** [comment]
I have confirmed this same behaviour on Azure CycleCloud 8.5 / Slurm template 3.0.5

**Comment by abdkha** [comment]
I can also confirm that this is existing on Slurm Cluster v.23.02.4-1, no matter which HPC Image I choose

**Comment by aditigaur4** [comment]
we have fixed in cyclecloud and azslurm 3.0.6 versions
