### ISSUE TITLE
AccountingStorageHost should be set to the scheduler hostname

### ISSUE THREAD

**Issue by xpillons** [Azure/cyclecloud-slurm#215]
Having the AccountingStorageHost set to localhost means that the `sacct` command can only be run where the `slurmdb` service is hosted. 
As a consequence, login node, compute node can't run sacct.

Updating the line below with the hostname of the scheduler will fix this. 
https://github.com/Azure/cyclecloud-slurm/blob/e877f657e0e4ff0e412804ef81073e02e25edb81/slurm/install/install.py#L243

**Comment by xpillons** [comment]
@aditigaur4 for reference

**Comment by aditigaur4** [comment]
Hello I have fixed this in: https://github.com/Azure/cyclecloud-slurm/pull/236
