### ISSUE TITLE
Add PMIX packages to be installed with Slurm

### ISSUE THREAD

**Issue by xpillons** [Azure/cyclecloud-slurm#216]
Slurm is built with PMIx v4 but PMIx is not published as packages and need to be built in the images used by the CycleCloud nodes.
Why not publishing PMIx packages and install them at the same time than the slurm ones ?
This will avoid lot's of issues with `srun --mpi=pmix` not running, as well as simplifying image built.

**Comment by aditigaur4** [comment]
pmix packages are now available in new images that would be released soon, those pmix packages are slurm compatible as well.
