### ISSUE TITLE
Update SuspendExcNodes to include nodes with KeepAlive=true

### ISSUE THREAD

**Issue by ryanhamel** [Azure/cyclecloud-slurm#23]
When we generate or regenerate the slurm.conf, we should add SuspendExcHosts= a node list of all nodes where KeepAlive is true in CycleCloud.

**Comment by tbugfinder** [comment]
Hi @ryanhamel 
I'm wondering if SuspendExecHosts is sufficient in a Slurm only configuration.
What's the benefit of having CycleCloud KeepAlive in addition?
Could `KeepAlive=true` be set only for few VMs within a nodearray?

**Comment by aditigaur4** [comment]
this is done.
