### ISSUE TITLE
azslurm cost does not handle blank admincomments

### ISSUE THREAD

**Issue by dougclayton** [Azure/cyclecloud-slurm#256]
For instance, a command such as `azslurm cost -s 2024-06-01 -e 2024-06-01 -o June-2024` will fail with `Error 'list index out of range': See the rest in the log file` if there are jobs where `admincomment` is blank.

**Comment by aditigaur4** [comment]
https://github.com/Azure/cyclecloud-slurm/pull/264

**Comment by aditigaur4** [comment]
This is fixed
