### ISSUE TITLE
Azslurm path is echoed with each autocomplete command

### ISSUE THREAD

**Issue by anhoward** [Azure/cyclecloud-slurm#258]
/etc/profile.d/azslurm_autocomplete.sh has a bad redirect that echoes the path of azslurm every time autocomplete is evaluated.

which azslurm 2>/dev/null || export PATH=$PATH:/root/bin

Should actually be 

which azslurm > /dev/null 2>&1 || export PATH=$PATH:/root/bin

**Comment by aditigaur4** [comment]
https://github.com/Azure/cyclecloud-slurm/pull/265

**Comment by aditigaur4** [comment]
This is merged
