### ISSUE TITLE
Slurm says jobs are running "R" however, nodes on CycleCloud machine are not up!!! Any idea?

### ISSUE THREAD

**Issue by robertosussex** [Azure/cyclecloud-slurm#261]
![image](https://github.com/Azure/cyclecloud-slurm/assets/37402138/25674fc0-08dc-4950-8525-8f2f10bc6c98)

Jobs reported as running....

![image](https://github.com/Azure/cyclecloud-slurm/assets/37402138/6070c933-28c8-47b3-8c4e-3dbff8fb4fd6)

scontrol shows that job stuck at Prolog!

![image](https://github.com/Azure/cyclecloud-slurm/assets/37402138/f118737e-f83c-4142-99f6-a66aa42e09c9)

Node is not available!!!!

![image](https://github.com/Azure/cyclecloud-slurm/assets/37402138/3f89194c-6bca-4009-b70b-758fca1a7a73)

after a while

![image](https://github.com/Azure/cyclecloud-slurm/assets/37402138/95225adc-d118-41eb-aa97-149c5b64e3d6)

==============================

Any idea n what may be going on?

Many thanks

Roberto

**Comment by aditigaur4** [comment]
Couple of clarifications.
1) which slurm and cyclecloud version?
2) is autoscaling turned on?
3) are you using any prolog scripts in your slurm.conf?

**Comment by robertosussex** [comment]
Hi,

slurm 20.11.7, 
Autoscale is enabled

![image](https://github.com/Azure/cyclecloud-slurm/assets/37402138/1d96b5a4-8738-4939-9b12-e82b71343f97)

in slurm.conf
![image](https://github.com/Azure/cyclecloud-slurm/assets/37402138/f5e765ea-efa3-461c-9723-6d2595bc3291)

slurm.prolog
![image](https://github.com/Azure/cyclecloud-slurm/assets/37402138/48c2e246-b2d9-4e34-adda-0d54878f75da)

slurmctld.prolog
![image](https://github.com/Azure/cyclecloud-slurm/assets/37402138/fa030bf3-1973-4895-a291-863e63800dea)

![image](https://github.com/Azure/cyclecloud-slurm/assets/37402138/26d40728-8f17-43d6-906a-968669ab1593)

![image](https://github.com/Azure/cyclecloud-slurm/assets/37402138/1543731a-c5dd-4ec4-a6c9-4ce51315c488)

==========================================================================

I will check about the CycleCloud version

Kind regards

Roberto

**Comment by robertosussex** [comment]
Can I check the version of cyclecloud from the GUI Cyclecloud portal?
![image](https://github.com/Azure/cyclecloud-slurm/assets/37402138/8c0362af-6959-4fbe-ba80-ee2d9b70e3a2)

Many thanks
Kind regards
Roberto

**Comment by robertosussex** [comment]
OK I was able to get into the box .......   :-)
Version === 8.2.2-1902

Kind regards
Roberto
