### ISSUE TITLE
The slurm-contribs package isn't getting installed in the latest Slurm project.

### ISSUE THREAD

**Issue by mangov99** [Azure/cyclecloud-slurm#285]
The slurm-contribs_version.rpm package is not being installed in the latest Slurm project, resulting in the seff command being unavailable. The customer wants to incorporate the seff command. Can we include slurm-contribs_version.arch.rpm? I noticed the RPM is available but not included in the installation script to install.

**Example**:
https://github.com/Azure/cyclecloud-slurm/blob/master/slurm/install/rhel.sh#L33

**Comment by aditigaur4** [comment]
Added this for the new version of slurm project
