### ISSUE TITLE
Syntax error in prolog.sh in 3.0.10/azure-slurm-pkg-3.0.10.tar.gz

### ISSUE THREAD

**Issue by pddro-Vestas** [Azure/cyclecloud-slurm#298]
Hello,

The prolog.sh script distributed in the latest version (see link below) has a syntax error in line 54: extra parenthesis _)_
https://github.com/Azure/cyclecloud-slurm/releases/download/3.0.10/azure-slurm-pkg-3.0.10.tar.gz

This completely breaks the cluster, given that the prolog script fails execution.

Thanks,
Pedro

**Comment by aditigaur4** [comment]
Please dont use this version yet, this still in our release testing.

That being said we are fixing it.

**Comment by aditigaur4** [comment]
updated the blobs,

**Comment by aditigaur4** [comment]
If you have cyclecloud using this version. then you could force CC to restage by deleting /opt/cycle_server/work/staging/projects/slurm on your CC VM.
