### ISSUE TITLE
migrate from 2.0.4 to 2.1.0

### ISSUE THREAD

**Issue by tbugfinder** [Azure/cyclecloud-slurm#31]
Hi,

how do I migrate my template based deployment from version 2.0.4 to 2.1.0?

Thanks

**Comment by anhoward** [comment]
The latest 7.9.3 release of CycleCloud includes the new project version. The easiest way to migrate would be to upgrade CycleCloud, then update your template to use project version 2.1.0 and point to Slurm version 18.08.9 or 19.05.5. You will need to re-deploy any running clusters to pick up the change on your master node.

**Comment by tbugfinder** [comment]
Thank You
