### ISSUE TITLE
Version mismatch between docker-rpmbuild and 00-build-slurm.sh

### ISSUE THREAD

**Issue by lmcdasm** [Azure/cyclecloud-slurm#32]
Hello.

I think there is a small bug in the 2.1.0 release.

when i do the following:

git clone <this project>
git checkout 2.1.0
git pull origin 2.1.0 (to be sure :P) 
cd cyclecloud-slurm
./docker-rpmbuild.sh

the container starts and builds the *.rpm and *.deb files into /blobs.
When i try to upload or build the project (cyclecloud project upload / cyclecoud project build), i get a file not found error looking for files in ./blobs that have a mismatched version:

project.ini shows the following defined in blobs section (_note the versions_):

[blobs]
Files = cyclecloud-api-7.9.2.tar.gz, job_submit_cyclecloud_centos_**18.08.9-1.so**, slurm-**18.08.9**-1.el7.x86_64.rpm, slurm-contribs-**18.08.9**-1.el7.x86_64.rpm, etc, etc, etc

however, after running docker-buildrpm.sh, and looking in ./blobs, here is the file listing:

[root@cyclecloud blobs]# ls -tlr
total 77336
-rw-r--r--. 1 root root    16362 Mar  5 19:23 cyclecloud-api-7.9.2.tar.gz
-rw-r--r--. 1 root root 13426172 Mar 15 09:24 slurm-**18.08.8**-1.el7.x86_64.rpm
-rw-r--r--. 1 root root   796360 Mar 15 09:24 slurm-perlapi-**18.08.8**-1.el7.x86_64.rpm
-rw-r--r--. 1 root root    78540 Mar 15 09:24 slurm-devel-**18.08.8**-1.el7.x86_64.rpm
-rw-r--r--. 1 root root     4996 Mar 15 09:24 slurm-example-configs-**18.08.8**-1.el7.x86_64.rpm
-rw-r--r--. 1 root root  1157424 Mar 15 09:24 slurm-slurmctld-**18.08.8**-1.el7.x86_64.rpm

_<as well, the files

cyclecloud-api-7.9.2.tar.gz 
job_submit_cyclecloud_ubuntu_19.05.5-1.so
job_submit_cyclecloud_centos_19.05.5-1.so

are not seemed to be built by the container with the docker-buildrpm.sh- i had to fetch it from the github releases page (wget)>_

When i changed the VERSION in the 00-build-slurm.sh script to 18.08.9 and re-ran the docker-rpmbuild.sh script, i can see the files are built with the version matching what the project.ini is looking for.

Im not 100% sure this is a bug  (if so i can do a PR if needed, seems simple)  or if  im missing something in the steps to build/deploy this project to locker.

Thanks,
Daniel

root@cyclecloud blobs]# ls -ltr
-rw-r--r--. 1 root root 13424068 Mar 15 09:47 slurm-18.08.9-1.el7.x86_64.rpm
-rw-r--r--. 1 root root   795780 Mar 15 09:47 slurm-perlapi-18.08.9-1.el7.x86_64.rpm
-rw-r--r--. 1 root root    78540 Mar 15 09:47 slurm-devel-18.08.9-1.el7.x86_64.rpm
-rw-r--r--. 1 root root     5000 Mar 15 09:47 slurm-example-configs-18.08.9-1.el7.x86_64.rpm
-rw-r--r--. 1 root root  1157280 Mar 15 09:47 slurm-slurmctld-18.08.9-1.el7.x86_64.rpm
-rw-r--r--. 1 root root   626380 Mar 15 09:47 slurm-slurmd-18.08.9-1.el7.x86_64.rpm
-rw-r--r--. 1 root root   670392 Mar 15 09:47 slurm-slurmdbd-18.08.9-1.el7.x86_64.rpm
-rw-r--r--. 1 root root   140940 Mar 15 09:47 slurm-libpmi-18.08.9-1.el7.x86_64.rpm
-rw-r--r--. 1 root root   116664 Mar 15 09:47 slurm-torque-18.08.9-1.el7.x86_64.rpm
-rw-r--r--. 1 root root     8476 Mar 15 09:47 slurm-openlava-18.08.9-1.el7.x86_64.rpm
-rw-r--r--. 1 root root    16612 Mar 15 09:47 slurm-contribs-18.08.9-1.el7.x86_64.rpm
-rw-r--r--. 1 root root   147612 Mar 15 09:47 slurm-pam_slurm-18.08.9-1.el7.x86_64.rpm
-rwxr-xr-x. 1 root root   198400 Mar 15 09:51 job_submit_cyclecloud_centos_18.08.9-1.so
-rwxr-xr-x. 1 root root   198400 Mar 15 09:51 job_submit_cyclecloud_ubuntu_18.08.9-1.so

**Comment by anhoward** [comment]
In general that's not really a script we expect most users to need to run, so it probably just got missed when we built the new artifacts for the latest release. We can bump the version in the script, but it's not a bug that would affect most customers just using the built-in Slurm cluster. Is there a specific reason you're trying to re-build the artifacts?

**Comment by anhoward** [comment]
I've just bumped the version in the script to match the release.

**Comment by lmcdasm** [comment]
Hey there.

Thanks alot - to be honest, i was doing some dissection of the jet pack package that is being used (and how the cycle-cloud-api package is getting baked in when nodes are started up - im looking to do some modifications to the jet pack part and we are building some "customer cluster" objects that we want our end users of our cycle cloud setup to be able to pick from using different projects in Cyclecloud and are wanting to drop some of our own packages - that is how i stumbled across it just playing around .)

i figured it was a minor thing :) thanks again.
