### ISSUE TITLE
Autoscale doesn't work properly with -N, only -n

### ISSUE THREAD

**Issue by anhoward** [Azure/cyclecloud-slurm#5]
When specifying -N <num_nodes> on a job, CycleCloud doesn't spin up the correct number of nodes and the job never runs. This is needed for MPI jobs wanting to use partial nodes.

**Comment by aplamada** [comment]
I experienced the same problem. In my simple 'salloc' or 'srun' examples `-N` is parsed as `-n` - in the cycleclouid GUI I noticed that the number of cores provisioned corresponds to `-N` .

**Comment by anhoward** [comment]
This is fixed in the 7.8 CycleCloud release. Release notes are [here](https://docs.microsoft.com/en-us/azure/cyclecloud/release-notes).
