### ISSUE TITLE
Confusing PCPU vs VCPU behavior

### ISSUE THREAD

**Issue by ryanhamel** [Azure/cyclecloud-slurm#54]
1) We need to make this project's use of physical vs virtual cores and how those are represented configurable.

2) CoresPerSocket does not seem to be calculated correctly. Here is a 32 vcpu, 16 pcpu VM but does not use 2 for the CoresPerSocket
Nodename=htc-[1-4] Feature=cloud STATE=CLOUD CPUs=16 CoresPerSocket=1 RealMemory=124518

**Comment by davestacionis** [comment]
See issue 50 also.  These topics are essentially the same.  Perhaps you want to merge them.
