### ISSUE TITLE
Node doesn't match existing scaleset when you add a new node to a node array

### ISSUE THREAD

**Issue by mangov99** [Azure/cyclecloud-slurm#58]
CycleCloud - 8.1.0-1275
Slurm -  19.05.8-1

Scenario:
1.  Submit a job to the HPC node array.
2. Increase max core count from UI and run scale (cyclecloud_slurm.sh scale) command.
3. Node which is in the acquiring state stuck with the below message:

{{{
This node does not match existing scaleset attributes: Configuration.cyclecloud.mounts.additional_nfs.export_path, Configuration.cyclecloud.mounts.additional_nfs.mountpoint
}}}

![Scaleset mismatch](https://user-images.githubusercontent.com/78450749/108426139-01765c80-7201-11eb-8c20-57c25a91c2a3.PNG)
![Node attributes - Good Node](https://user-images.githubusercontent.com/78450749/108426136-00ddc600-7201-11eb-8815-925c81b51af5.PNG)
![Node attributes - Failed Node](https://user-images.githubusercontent.com/78450749/108426137-01765c80-7201-11eb-9d59-1799a2c7beff.PNG)

**Comment by dougclayton** [comment]
This will be fixed in 8.1.1.

**Comment by dougclayton** [comment]
Upgrading to CycleCloud 8.1.1 fixes this.
