### ISSUE TITLE
Slurm accounting is disabled on the headnode

### ISSUE THREAD

**Issue by anhoward** [Azure/cyclecloud-slurm#6]
The sacct command doesn't work by default on the head node. Accounting is useful for debugging issues. The option to turn it on should be exposed via the cluster template.

**Comment by tbugfinder** [comment]
I'd need that feature also.

**Comment by javierbq** [comment]
+1

**Comment by yellowhat** [comment]
+1

**Comment by anhoward** [comment]
This is now  a supported configuration and will be included as part of the CycleCloud 8.1 release.

https://github.com/Azure/cyclecloud-slurm/pull/43
