### ISSUE TITLE
Question regarding /sched default size

### ISSUE THREAD

**Issue by yuriyarabskyy** [Azure/cyclecloud-slurm#62]
I noticed that by default /sched mount in the slurm.txt template has 1T of memory. But as far as I understood it only contained some slurm and cyclecloud configurations. Why does it need all this memory then?

**Comment by anhoward** [comment]
Great catch; I'm guessing this was copied from another configuration somewhere. /sched shouldn't need 1TB of disk space. I'll adjust this down to a more reasonable value.

**Comment by anhoward** [comment]
Fixed in https://github.com/Azure/cyclecloud-slurm/commit/9ed804dc11298bf935118d55be0fbf6fab5127ce
