### ISSUE TITLE
Slurm Accounting add cluster fails on cluster terminate/restart

### ISSUE THREAD

**Issue by themorey** [Azure/cyclecloud-slurm#63]
Slurm proj: 2.4.4
Slurm ver:  20.11.4-1
CC ver:  8.1.0-1275

A Slurm cluster connected to MariaDB service in Azure will fail to restart cleanly when terminiated/restarted.  The following error is seen:

    ================================================================================
    Error executing action `run` on resource 'bash[Add cluster to slurmdbd]'
    ================================================================================
    
    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '1'
    ---- Begin output of "bash"  "/tmp/chef-script20210401-1390-h8kq8x" ----
    STDOUT: This cluster ucla-slurm-docker-grafana already exists.  Not adding.
    STDERR: 
    ---- End output of "bash"  "/tmp/chef-script20210401-1390-h8kq8x" ----
    Ran "bash"  "/tmp/chef-script20210401-1390-h8kq8x" returned 1
    
    Resource Declaration:
    ---------------------
    # In /opt/cycle/jetpack/system/chef/cache/cookbooks/slurm/recipes/accounting.rb
    
     77: bash 'Add cluster to slurmdbd' do
     78:     code <<-EOH
     79:         sacctmgr -i add cluster #{clustername} && touch /etc/slurmdbd.configured 
     80:         EOH
     81:     not_if { ::File.exist?('/etc/slurmdbd.configured') }
     82:     not_if "sleep 5 && sacctmgr show cluster | grep #{clustername}" 
     83: end
     84: 
    
    Compiled Resource:
    ------------------
    # Declared in /opt/cycle/jetpack/system/chef/cache/cookbooks/slurm/recipes/accounting.rb:77:in `from_file'
    
    bash("Add cluster to slurmdbd") do
      action [:run]
      default_guard_interpreter :default
      command nil
      backup 5
      returns 0
      user nil
      interpreter "bash"
      declared_type :bash
      cookbook_name "slurm"
      recipe_name "accounting"
      code "        sacctmgr -i add cluster UCLA-slurm-docker-grafana && touch /etc/slurmdbd.configured \n"
      domain nil
      not_if { #code block }
      not_if "sleep 5 && sacctmgr show cluster | grep UCLA-slurm-docker-grafana"
    end
    
    System Info:
    ------------
    chef_version=13.12.14
    platform=centos
    platform_version=7.7.1908
    ruby=ruby 2.5.7p206 (2019-10-01 revision 67816) [x86_64-linux]
    program_name=chef-solo worker: ppid=1385;start=17:48:00;
    executable=/opt/cycle/jetpack/system/embedded/bin/chef-solo
    

    Running handlers:
      - CycleCloud::ExceptionHandler
      - CycleCloud::ExceptionHandler
    Running handlers complete
    Chef Client failed. 9 resources updated in 16 seconds
    Error: A problem occurred while running Chef, check chef-client.log for details

On the scheduler node I see the cluster already exists in sacctmgr:
```
   [cyclecloud@glinc5zuux6 ~]$ sacctmgr list cluster
   Cluster     ControlHost  ControlPort   RPC     Share GrpJobs       GrpTRES GrpSubmit MaxJobs       MaxTRES MaxSubmit        MaxWall                  QOS   Def QOS 
---------- --------------- ------------ ----- --------- ------- ------------- --------- ------- ------------- --------- ----------- -------------------- --------- 
ucla-slur+                            0  9216         1                                                                                           normal           
```

I suspect scheduler.rb line 77 needs a check if cluster exists before trying to add the cluster.

**Comment by sla23** [comment]
Thanks for reporting this. I am seeing the same issue in Slurm proj: 2.4.5.

**Comment by anhoward** [comment]
I'm taking a closer look at this, but based on the log message I"m wondering if it's a case sensitivity issue:

`STDOUT: This cluster ucla-slurm-docker-grafana already exists.  Not adding.`

vs:

`not_if "sleep 5 && sacctmgr show cluster | grep UCLA-slurm-docker-grafana"`
