### ISSUE TITLE
SLURM 2.4.8 pmix libs are not included

### ISSUE THREAD

**Issue by garvct** [Azure/cyclecloud-slurm#68]
SLURM 2.4.8 is compiled with pmix support so MPI libraries will interface correctly with SLURM srun.
It seems that SLURM 2.4.8 expects the pmix libs to be install on the compute nodes at /opt/pmix/v3, but these do not  exist and need to be built (e.g cluster-init project).

#!/bin/bash

cd ~/
mkdir -p /opt/pmix/v3
apt install -y libevent-dev
tar xvf $CYCLECLOUD_SPEC_PATH/files/openpmix-3.1.6.tar.gz
cd openpmix-3.1.6
#mkdir -p pmix/build/v3 pmix/install/v3
#cd pmix
#git clone https://github.com/openpmix/openpmix.git source
#cd source/
#git branch -a
#git checkout v3.1
#git pull
./autogen.sh
#cd ../build/v3/
./configure --prefix=/opt/pmix/v3
make -j install >/dev/null

Can there pmix libs be included with SLURM versions built with pmix support (SLURM 2.4.8+)?

**Comment by aditigaur4** [comment]
This has been fixed in later versions.
