### ISSUE TITLE
Some modern slurm features not supported

### ISSUE THREAD

**Issue by mjclarke94** [Azure/cyclecloud-slurm#82]
With the currently supported version of Slurm, the `slurmrestd` service can be built by the addition of a few dependencies in the rpmbuild stage and the addition of an rpmbuild flag:
```
RUN yum install -y http-parser-devel json-c-devel
RUN rpmbuild  --define "_with_slurmrestd 1" -ta ${SLURM_PKG}
```

How this would then be added to chef/cloud-init is unfortunately beyond me!

There are also several cloud focused developments (such as burstbuffer/lua for staging of files which is useful when using cloud compute resources) and commonly required features (job script capturing, parsable account queries, etc) which are unavailable due to them only being available in Slurm 21.08.

Is there a timeline for when the slurm version will be bumped to the latest, and is there any scope for enabling additional features like `slurmrestd`?

**Comment by mjclarke94** [comment]
Interesting, I'll give this a try. Would you be able to point me to the cyclecloud documentation which details how to add projects? Whilst I can see how I would go about modifying this repo in order to have a different slurm build, I can't quite work out how to then feed that into a given cyclecloud deployment...apologies for the naive questions!

**Comment by tbugfinder** [comment]
Basically this repo is a cluster template which can be used to define a cluster in code and import it.
https://docs.microsoft.com/en-us/azure/cyclecloud/tutorials/modify-cluster-template?view=cyclecloud-8#import-the-new-cluster-template

Usually after cloning this repo, I'm adding a blobs folder and download any assets attached to a release.
This filenames go into the blobs section of project.ini
https://github.com/Azure/cyclecloud-slurm/blob/master/project.ini#L7-L8

Having this in place, you can build your custom Slurm on a build host and move the files to the blobs folder and extend the list in project.ini.

Depending on the version in scope the slurm default version can be updated, too.
https://github.com/Azure/cyclecloud-slurm/blob/master/project.ini#L25

As the custom slurm build might add additional packages the Chef cookbooks might need a tweak.
This list of rpms or packages can be extended in this file (verify your OS).
https://github.com/Azure/cyclecloud-slurm/blob/master/specs/default/chef/site-cookbooks/slurm/recipes/_install.rb#L73

Master and execution nodes have different Chef cookbooks (profiles). So check, what needs to be updated where.
https://github.com/Azure/cyclecloud-slurm/blob/master/specs/default/chef/site-cookbooks/slurm/recipes/_install.rb#L20

Once the cookbooks and blobs are in place and updated those can be uploaded into the Azure BLOB storage.
```cyclecloud project upload```

After that create your cluster using
```
cyclecloud import_template -f templates/myownslurmcluster.template.txt
```

This "guide" might not be complete and needs some verification in your test environment. So I'm happy to answer any additional question(s).

I should sum this up in a blog post :-D

**Comment by mjclarke94** [comment]
Perfect, thanks very much for that :) I've blocked out tomorrow for working on this so will give it a go...it wouldn't be a new slurm release without some interesting edge cases to contend with so there's a good chance I'll be taking you up on the additional questions!

I _think_ I've spotted an issue with the rpmbuild script but will open a separate issue/PR.

**Comment by aditigaur4** [comment]
Hello new slurm builds include both slurmrestd and lua integrations. custom builds should no longer be necessary.
